### PR TITLE
[4.14 lts] Various hardening to be analysed.

### PR DESCRIPTION
**Pull request by HacKurx**
Hi,

Here are some modifications, I leave you free to take what you want:
https://github.com/HacKurx/linux-hardened/commits/4.14-lts

Best regards.

### CODE REVIEW

**Comment by anthraxx** [comment]
thanks a lot for the contribution, I will pull in some patches batch by batch very soon.

**Comment by HacKurx** [comment]
@anthraxx You're welcome. I'm in favor of using "default n" for more visibility but it's up to you. 

I added the commit a3bdc9b for record the access to the SUID, there will be a compilation warning (FIXME).

**Comment by anthraxx** [comment]
For future contribution, especially when it's more then a simple kconfig change, please create separated pull requests.
It's easier to track and discuss.

**Comment by HacKurx** [comment]
Okay, no problem.

**Comment by HacKurx** [comment]
I'm closing it for visibility.

**Pull request closed without merging**
