### PR TITLE
Turn off kexec

### PR DESCRIPTION
**Pull request by HacKurx**
Turn off kexec, even if it's built in.

This is a recommended settings by the Kernel Self Protection Project :
https://kernsec.org/wiki/index.php/Kernel_Self_Protection_Project/Recommended_Settings#sysctls

### CODE REVIEW

**Comment by madaidan** [comment]
The kernel.kexec_load_disabled sysctl can't be set back to 0 once it's enabled. This PR would force kexec to be disabled at all times and makes it non-optional. This would be best left for something the user to do themselves rather than forcing it on them.

**Comment by HacKurx** [comment]
> The kernel.kexec_load_disabled sysctl can't be set back to 0 once it's enabled. This PR would force kexec to be disabled at all times and makes it non-optional. This would be best left for something the user to do themselves rather than forcing it on them.

Isn't the purpose of linux-hardened to reduce the attacking surface? Shouldn't the default installation be secured?

**Comment by XHDR** [comment]
My humble two cents would be that having `CONFIG_KEXEC` be defaulted to N, rather than crippling it in this way. There's a fair share of Kconfig related commits already, and that kexec being something that's unlikely be be a requirement for anyone running a "hardened" kernel. Thus I think it should be fine to have it default off in builds. That way, if there's actually someone who'd actually need it, they can just build the kernel with it enabled.

**Comment by HacKurx** [comment]
So it depends on #28.
It should, however, have "__read_only" protection for generic kernels.

**Comment by anthraxx** [comment]
`kexec_load_disabled` ? You can't `__read_only` that, its supposed to be change-abl via sysctl and `proc_dointvec_minmax` with `SYSCTL_ONE` makes it basically one-time-settable. This wouldn't work with `__read_only` either.

**Comment by HacKurx** [comment]
> `kexec_load_disabled` ? You can't `__read_only` that, its supposed to be change-abl via sysctl and `proc_dointvec_minmax` with `SYSCTL_ONE` makes it basically one-time-settable. This wouldn't work with `__read_only` either.

[So this is wrong?](https://github.com/jameshilliard/linux-grsec/blame/c3606ec9678506017e2d56a8064e9337ba3bcb9a/kernel/kexec_core.c#L854)

**Comment by tsautereau-anssi** [comment]
No, `__read_only` is entirely different in grsecurity.

**Pull request closed without merging**
