### PR TITLE
Harden module auto-loading

### PR DESCRIPTION
**Pull request by madaidan**
This creates a CONFIG_SECURITY_MODHARDEN option and when enabled, restricts module auto-loading to root. This is based on GRKERNSEC_MODHARDEN.

### CODE REVIEW

**Comment by Bernhard40** [comment]
I'm not sure if this is supposed to be so simple while comparing with [last proposal for upstreaming](https://lore.kernel.org/kernel-hardening/alpine.LFD.2.20.1711281041040.13133@localhost/T/#e5f29fd2b86b0b28949bb543dfde17dedd0419a71).

**Comment by madaidan** [comment]
The other things in that proposal aren't really important.

It adds a sysctl for controlling this functionality instead of a kernel config option and a way to control it per-task which is mostly pointless for linux-hardened as popular sandboxes won't use features that require other kernels.

The only thing there that does seem useful is allowing processes with CAP_NET_ADMIN to load certain network related modules but even then, that isn't too important either.

**Comment by Bernhard40** [comment]
If it breaks applications then it's quite important. Also it should check for `CAP_SYS_MODULE`.

**Comment by anthraxx** [comment]
yes, it should have a runtime knot and a kconfig value to define the DEFAULT. I also agree if it doesn't follow checking `CAP_SYS_MODULE` then it breaks expected capability behavior.

**Comment by madaidan** [comment]
https://github.com/anthraxx/linux-hardened/pull/19/commits/689e7b814c983008a5c1ad234842236e24acf72c makes it check for CAP_SYS_MODULE. I don't know how to create a sysctl knob though.

**Comment by madaidan** [comment]
Why was this closed? Because no sysctl knob?

**Comment by anthraxx** [comment]
Just GH doing weird stuff based on some meta triggers in commit messages

**Comment by adrelanos** [comment]
Could you reopen please?

**Comment by madaidan** [comment]
I figured out how to add a sysctl knob https://github.com/madaidan/linux-hardened/commit/7323c4585c6194a2f31ea71d40109ed7c8e8772d

Anything else?

**Comment by anthraxx** [comment]
Can you re-send the PR against master?

**Comment by madaidan** [comment]
Done https://github.com/anthraxx/linux-hardened/pull/23

**Pull request closed without merging**
